# Generated by Django 6.0.5 on 2026-05-29 15:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=32, validators=[apps.core.validators.validate_mobile]),
        ),
    ]
