# Generated by Codex on 2026-05-31

from django.db import migrations, models


def copy_active_status_to_workflow(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(is_active=True).update(workflow_state='HIRED')
    Employee.objects.filter(is_active=False).update(workflow_state='NOT_ACCEPTED')


def copy_workflow_to_active_status(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(workflow_state='HIRED').update(is_active=True)
    Employee.objects.exclude(workflow_state='HIRED').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workflow_state',
            field=models.CharField(
                choices=[
                    ('APPLICATION_RECEIVED', 'Application Received'),
                    ('INTERVIEW_SCHEDULED', 'Interview Scheduled'),
                    ('HIRED', 'Hired'),
                    ('NOT_ACCEPTED', 'Not Accepted'),
                ],
                db_index=True,
                default='APPLICATION_RECEIVED',
                max_length=32,
            ),
        ),
        migrations.RunPython(copy_active_status_to_workflow, copy_workflow_to_active_status),
    ]
