# Generated by Codex on 2026-05-31

from django.db import migrations


def mark_admin_and_hr_employees_hired(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee.objects.filter(user__role__in=['ADMIN', 'HR_MANAGER']).update(
        workflow_state='HIRED',
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_workflow_state'),
    ]

    operations = [
        migrations.RunPython(mark_admin_and_hr_employees_hired, migrations.RunPython.noop),
    ]
